import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {cn} from "../lib/utils"
import SideNavbar from "@/components/SideNavBar";
import NavBar from '@/components/NavBar';
import "../app/scroll.css"
import ReduxProvider from "@/Redux/provider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("flex items-start justify-start h-screen w-screen  overflow-y-hidden bg-[#F8F8F8]  ",inter.className)}>
      <ReduxProvider>
        <SideNavbar />
        <div id='scrollbar-hide' className='h-screen w-full overflow-x-scroll overflow-y-auto'>
          <NavBar/>
          {children}
        </div>
      </ReduxProvider>
      </body>
    </html>
  )
}
